#!/usr/bin/env python3
"""
Copilot Code Review Script
Provides basic code review functionality for GitHub PRs
"""

import os
import requests
import sys

def main():
    pr_number = os.getenv('PR_NUMBER')
    if not pr_number:
        print('ℹ️  No PR number - skipping review')
        return

    print(f'Reviewing PR #{pr_number}...')

    headers = {'Authorization': f'token {os.getenv("GITHUB_TOKEN")}'}
    pr_url = f'https://api.github.com/repos/{os.getenv("GITHUB_OWNER")}/{os.getenv("GITHUB_REPO")}/pulls/{pr_number}'

    try:
        pr_response = requests.get(pr_url, headers=headers)
        if pr_response.status_code != 200:
            print(f'⚠️  Failed to fetch PR: {pr_response.status_code}')
            return

        pr_data = pr_response.json()
        title = pr_data.get('title', 'Unknown PR')

        review_body = f'''## 🤖 Copilot Code Review

### Analysis
PR: **{title}**

### Recommendations
- Review code for potential issues
- Check test coverage
- Verify security best practices
- Consider performance implications

*Generated by GitHub Copilot*
'''

        comment_url = f'https://api.github.com/repos/{os.getenv("GITHUB_OWNER")}/{os.getenv("GITHUB_REPO")}/issues/{pr_number}/comments'
        response = requests.post(comment_url, headers=headers, json={'body': review_body})

        if response.status_code == 201:
            print('✅ Basic Copilot review posted to PR')
        else:
            print(f'⚠️  Failed to post review: {response.status_code}')

    except Exception as e:
        print(f'⚠️  Review failed: {e}')
        sys.exit(1)

if __name__ == '__main__':
    main()