#!/usr/bin/env python3
"""
Copilot Code Review Script (Swift Edition)
Standardized for planner-app with Swift-specific context.
"""

import os
import requests
import sys
import random


def get_mock_ai_review(title, files):
    """Generate a mock AI review when real APIs are not available"""
    reviews = [
        "Good structure. Consider using dependency injection for better testability.",
        "Check for potential retain cycles in closures. Otherwise, code looks clean.",
        "Ensure properly handling of optionals. Guard statements are used effectively.",
        "Concurrency handling with async/await looks correct. Verify MainActor usage.",
        "Extensions are well-organized. Consider moving large extensions to separate files.",
    ]
    return random.choice(reviews)


def main():
    pr_number = os.getenv("PR_NUMBER")
    if not pr_number:
        print("ℹ️  No PR number - skipping review")
        return

    print(f"Reviewing PR #{pr_number} (Swift Context)...")

    headers = {"Authorization": f"token {os.getenv('GITHUB_TOKEN')}"}
    pr_url = f"https://api.github.com/repos/{os.getenv('GITHUB_OWNER')}/{os.getenv('GITHUB_REPO')}/pulls/{pr_number}"

    try:
        pr_response = requests.get(pr_url, headers=headers, timeout=30)
        if pr_response.status_code != 200:
            print(f"⚠️  Failed to fetch PR: {pr_response.status_code}")
            return

        pr_data = pr_response.json()
        title = pr_data.get("title", "Unknown PR")

        # Get PR files
        diff_url = f"{pr_url}/files"
        diff_response = requests.get(diff_url, headers=headers, timeout=30)
        files = diff_response.json() if diff_response.status_code == 200 else []
        file_list = [f["filename"] for f in files[:5]] if files else ["No files found"]

        # API Configuration
        openai_key = os.getenv("OPENAI_API_KEY")
        anthropic_key = os.getenv("ANTHROPIC_API_KEY")

        # Configurable Models (Safe Defaults)
        openai_model = os.getenv("OPENAI_MODEL", "gpt-4")
        anthropic_model = os.getenv("ANTHROPIC_MODEL", "claude-3-opus-20240229")

        ai_available = openai_key or anthropic_key
        review_content = ""

        if ai_available:
            print(
                f"✅ AI APIs available - reviewing with {openai_model if openai_key else anthropic_model}"
            )

            # Swift-Specific Prompt
            analysis_prompt = (
                f"Analyze this Swift PR: {title}\n\n"
                f"Changes: {file_list}\n\n"
                "Provide a code review focusing on:\n"
                "1) Swift Best Practices (ARC, Value Types, Protocol extensions)\n"
                "2) Concurrency Safety (Actors, async/await)\n"
                "3) iOS Performance (View rendering, Memory usage)\n"
                "4) Security (Data storage, Networking)"
            )

            try:
                if openai_key:
                    from openai import OpenAI

                    client = OpenAI(api_key=openai_key)
                    response = client.chat.completions.create(
                        model=openai_model,
                        messages=[{"role": "user", "content": analysis_prompt}],
                        max_tokens=600,
                    )
                    review_content = response.choices[0].message.content
                elif anthropic_key:
                    from anthropic import Anthropic

                    client = Anthropic(api_key=anthropic_key)
                    response = client.messages.create(
                        model=anthropic_model,
                        max_tokens=600,
                        messages=[{"role": "user", "content": analysis_prompt}],
                    )
                    review_content = response.content[0].text
            except Exception as e:
                print(f"⚠️  AI API failed: {e}")
                review_content = get_mock_ai_review(title, file_list)
        else:
            print("🔄 Using mock AI review")
            review_content = get_mock_ai_review(title, file_list)

        review_body = f"""## 🤖 Copilot Code Review (Swift)

### Analysis
PR: **{title}**
Model: `{openai_model if openai_key else (anthropic_model if anthropic_key else "Mock")}`

### AI Review
{review_content}

### Swift Recommendations
- Verify ARC and retain cycles
- Check MainActor usage for UI updates
- Validate optional unwrapping

*Generated by GitHub Copilot*
"""

        comment_url = f"https://api.github.com/repos/{os.getenv('GITHUB_OWNER')}/{os.getenv('GITHUB_REPO')}/issues/{pr_number}/comments"
        requests.post(
            comment_url, headers=headers, json={"body": review_body}, timeout=30
        )
        print("✅ Review posted")

    except Exception as e:
        print(f"⚠️  Review failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
