# SwiftLint Configuration for Quantum Workspace
# Root configuration file for all Swift projects

disabled_rules:
  # Allow tracking work-in-progress without failing strict lint runs
  - todo
  # Tests and generated fixtures frequently exceed simple thresholds
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - unused_optional_binding
  - for_where
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - empty_count
  - attributes
  # Remove identifier_name from disabled_rules since we configure it below
  # - identifier_name

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - empty_count
  - explicit_init
  - literal_expression_end_indentation
  - modifier_order
  - redundant_nil_coalescing

included:
  - Projects
  - Shared

excluded:
  - "**/.autofix_backups"
  - "**/.build"
  - "**/DerivedData"
  - "**/Generated"
  - "**/node_modules"
  - "**/.swiftpm"
  - "**/Package.swift"
  - "**/*.generated.swift"

identifier_name:
  allowed_symbols: [i, j, id]

line_length:
  warning: 200
  error: 240

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

large_tuple:
  warning: 3
  error: 4

reporter: "xcode"