codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 60%
        threshold: 1%
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 1%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

github_checks:
  annotations: true