#!/usr/bin/env python3
"""
Git Operations - Git-related operations for workflow recovery.

Extracted from ai_workflow_recovery.py for modularity.
Contains git operations:
- Commit and push fixes
- Trigger workflow reruns
"""

import logging
import subprocess
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .ai_workflow_recovery import WorkflowFailure

logger = logging.getLogger(__name__)


def commit_and_push_fixes(repo_path: Path, failure: "WorkflowFailure") -> bool:
    """Commit and push the applied fixes."""
    try:
        # Add all changes
        subprocess.run(["git", "add", "."], cwd=repo_path, check=True)

        # Check if there are changes to commit
        result = subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=repo_path)

        if result.returncode == 0:
            logger.info("ℹ️ No changes to commit")
            return True

        # Commit with descriptive message
        commit_msg = f"""🤖 AI Auto-Fix: {failure.error_type}

✅ AI Analysis Results:
- Error Type: {failure.error_type}
- Confidence: {failure.confidence_score:.1%}
- Fix Applied: {failure.suggested_fix}

🧠 Learning System:
- Pattern Recognition: Active
- Auto-fix Generation: Successful
- Retry #{failure.retry_count + 1}

Generated by AI Workflow Recovery System
Timestamp: {datetime.now().isoformat()}"""

        subprocess.run(["git", "commit", "-m", commit_msg], cwd=repo_path, check=True)

        # Push changes
        subprocess.run(["git", "push"], cwd=repo_path, check=True)

        logger.info("✅ Changes committed and pushed successfully")
        return True

    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to commit/push: {e}")
        return False


def trigger_workflow_rerun(repo_path: Path) -> bool:
    """Trigger a new workflow run."""
    try:
        # Create a small change to trigger workflow
        trigger_file = repo_path / ".ai_workflow_trigger"

        with open(trigger_file, "w") as f:
            f.write(f"AI Workflow Recovery trigger: {datetime.now().isoformat()}\n")

        # Commit trigger
        subprocess.run(
            ["git", "add", ".ai_workflow_trigger"], cwd=repo_path, check=True
        )
        subprocess.run(
            ["git", "commit", "-m", "🔄 AI Workflow Recovery: Trigger re-run"],
            cwd=repo_path,
            check=True,
        )
        subprocess.run(["git", "push"], cwd=repo_path, check=True)

        logger.info("🔄 Workflow re-triggered successfully")
        return True

    except Exception as e:
        logger.error(f"Failed to trigger workflow: {e}")
        return False


def get_repo_info(repo_path: Path) -> tuple:
    """Extract repository owner and name from git config."""
    try:
        result = subprocess.run(
            ["git", "config", "--get", "remote.origin.url"],
            capture_output=True,
            text=True,
            cwd=repo_path,
        )
        url = result.stdout.strip()

        import re

        match = re.search(r"github\.com[:/]([^/]+)/([^/]+)", url)
        if match:
            owner = match.group(1)
            repo = match.group(2).replace(".git", "")
            return owner, repo
    except Exception:
        pass

    return "unknown", "unknown"
