//
//  FinancialInsightModels.swift
//  MomentumFinance
//
//  Created by Daniel Stevens on 6/5/25.
//  Copyright © 2025 Daniel Stevens. All rights reserved.
//

import Foundation
import SwiftUI

/// Data models and enums for financial insights and analysis results
public struct FinancialInsightModels {
    // This serves as a namespace for insight-related types
}

// MARK: - Financial Insight Model

/// Represents a specific financial insight generated by the analysis
public struct FinancialInsight: Identifiable, Hashable {
    public let id = UUID()
    public let title: String
    public let description: String
    public let priority: InsightPriority
    public let type: InsightType
    public let relatedAccountId: String?
    public let relatedTransactionId: String?
    public let relatedCategoryId: String?
    public let relatedBudgetId: String?
    public let visualizationType: VisualizationType?
    public let data: [(String, Double)]

    public init(
        title: String,
        description: String,
        priority: InsightPriority,
        type: InsightType,
        relatedAccountId: String? = nil,
        relatedTransactionId: String? = nil,
        relatedCategoryId: String? = nil,
        relatedBudgetId: String? = nil,
        visualizationType: VisualizationType? = nil,
        data: [(String, Double)] = []
    ) {
        self.title = title
        self.description = description
        self.priority = priority
        self.type = type
        self.relatedAccountId = relatedAccountId
        self.relatedTransactionId = relatedTransactionId
        self.relatedCategoryId = relatedCategoryId
        self.relatedBudgetId = relatedBudgetId
        self.visualizationType = visualizationType
        self.data = data
    }

    // MARK: - Hashable Conformance

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    public static func == (lhs: FinancialInsight, rhs: FinancialInsight) -> Bool {
        lhs.id == rhs.id
    }
}

// MARK: - Insight Priority Enum

/// Priority levels for financial insights with visual styling
public enum InsightPriority: String, CaseIterable, Comparable {
    case critical
    case high
    case medium
    case low

    /// Color associated with the priority level
    public var color: Color {
        switch self {
        case .critical:
            .red
        case .high:
            .orange
        case .medium:
            .blue
        case .low:
            .green
        }
    }

    /// System icon for the priority level
    public var icon: String {
        switch self {
        case .critical:
            "exclamationmark.triangle.fill"
        case .high:
            "exclamationmark.circle.fill"
        case .medium:
            "info.circle.fill"
        case .low:
            "checkmark.circle.fill"
        }
    }

    // MARK: - Comparable Implementation

    /// Comparable implementation (critical > high > medium > low)
    public static func < (lhs: InsightPriority, rhs: InsightPriority) -> Bool {
        let order: [InsightPriority] = [.low, .medium, .high, .critical]
        guard let lhsIndex = order.firstIndex(of: lhs),
              let rhsIndex = order.firstIndex(of: rhs)
        else {
            return false
        }
        return lhsIndex < rhsIndex
    }
}

// MARK: - Insight Type Enum

/// Types of financial insights that can be generated
public enum InsightType: String, CaseIterable {
    case spendingPattern
    case positiveSpendingTrend
    case anomaly
    case budgetAlert
    case budgetInsight
    case budgetRecommendation
    case subscriptionDetection
    case forecast
    case optimization

    /// System icon for the insight type
    var icon: String {
        switch self {
        case .spendingPattern:
            "chart.line.uptrend.xyaxis"
        case .positiveSpendingTrend:
            "arrow.down.circle"
        case .anomaly:
            "exclamationmark.triangle"
        case .budgetAlert:
            "chart.pie.fill"
        case .budgetInsight:
            "chart.bar.fill"
        case .budgetRecommendation:
            "plus.circle"
        case .subscriptionDetection:
            "calendar.badge.clock"
        case .forecast:
            "chart.xyaxis.line"
        case .optimization:
            "bolt.circle"
        }
    }
}

// MARK: - Visualization Type Enum

/// Types of data visualizations that can be used for insights
public enum VisualizationType {
    case barChart
    case lineChart
    case pieChart
    case progressBar
    case boxPlot
}
